Test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,6 +24,11 @@ on:
         description: "Build Version"
         required: true
         default: 0.0.1
+      continuousIntegration:
+        description: "Continuous Integration"
+        required: true
+        type: bool
+        default: false
 
 jobs:
   build_test:
@@ -45,7 +50,21 @@ jobs:
       - name: Run test
         run: npm test
 
+      - name: Build App
+        run: |
+          if [ ${{ github.event.inputs.buildEnvironment }} == "dev" ]; then
+            echo "Will build dev build"
+          elif [ ${{ github.event.inputs.buildEnvironment }} == "stage" ]; then
+            echo "Will build stage build"
+          elif [ ${{ github.event.inputs.buildEnvironment }} == "prod" ]; then
+            echo "Will build prod build"
+          else
+            echo "Invalid Environment"
+            exit 22
+          fi
+
   build_container:
+    if: github.event.input.continuousIntegration == true
     runs-on: ubuntu-latest
     needs: [build_test]
 
